{% set name = "nestedtext" %}
{% set version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nestedtext-{{ version }}.tar.gz
  sha256: 01f0a7b9c7339e7ca540c46f7d41d68a45fa067d7a9d873cebaac8157c9ce6dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - inform >=1.28

test:
  imports:
    - nestedtext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: human readable and writable data interchange format
  description: |
    NestedText is a file format for holding structured data. It is similar in
    concept to JSON, except that NestedText is designed to make it easy for
    people to enter, edit, or view the data directly. It organizes the data into
    a nested collection of name-value pairs, lists, and strings. The syntax is
    intended to be very simple and intuitive for most people.
  license: MIT
  license_file: LICENSE
  home: https://nestedtext.org
  doc_url: https://nestedtext.org
  dev_url: https://github.com/KenKundert/nestedtext


extra:
  recipe-maintainers:
    - KenKundert
